### ISSUE TITLE
Support OIDC groups in AdminList

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#2125]
Would like to specify groups instead of users in the AdminList for OIDC. The would make user management easier.

```yaml
authorization:
  admin_list:
    enabled: true
    users:
      - x@y.com
```

```yaml
authorization:
  admin_list:
    enabled: true
    groups:
      - xyz
```
