### ISSUE TITLE
OpenAI QnA module settings are weird

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2432]
Hi,

This module has a very different configuration compared to others, let say the transformers QnA for instance.

1) Its settings are defined inside the class, as if it were a vectorizer
This requires to define the QnA settings at the time of creation of the class: no way to change the maxTokens or temperature on the go.

https://weaviate.io/developers/weaviate/current/reader-generator-modules/qna-openai.html#how-to-configure
```{
  "classes": [
    {
      "class": "Document",
      "description": "A class called document",
      "vectorizer": "text2vec-openai",
      "moduleConfig": {
        "qna-openai": {
          "model": "text-davinci-002",
          "maxTokens": 16,
          "temperature": 0.0,
          "topP": 1,
          "frequencyPenalty": 0.0,
          "presencePenalty": 0.0
        }
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content that will be vectorized",
          "name": "content"
        }
      ]
    }
  ]
}
```

2) The module is not defined in the docker file, as is the transformer QnA
```
---
version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image:
      semitechnologies/weaviate:1.16.6
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,qna-openai'
      OPENAI_APIKEY: sk-foobar # this parameter is optional, as you can also provide it at insert/query time
      CLUSTER_HOSTNAME: 'node1'
```

3) Model settings are not aligned with the OpenAI vectorizer's

`"model": "text-davinci-002",
`

vs

```
"text2vec-openai": {
          "model": "davinci",
          "type": "text"
        }
```
