### ISSUE TITLE
Random results when using OR and limit

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate#2575]
Description:

Executing this query multiple times will return 1 to 3 documents:

```
{
  Get {
    P_4f1d3b4a_1847_4548_be5a_53b814b104db_predictions(
      where: {operator: Or, operands: [
{path: ["id"], operator: Equal, valueString: "daa9ac85-615e-4ab8-8677-07ab31601e87"}, 
{path: ["id"], operator: Equal, valueString: "578b0588-d0f7-4d70-a7f9-c3b3d41f577e"}, 
{path: ["id"], operator: Equal, valueString: "a09b09c5-1c5c-4fac-b873-606851993f12"}]}
limit: 3    
    ) {
      _additional {
        id
      }
    }
  }
}
```

The expected results is always 3 documents.

Setting the limit to 10 appears to give the correct results consistently.

To reproduce:

1. Setup weaviate with the following settings:
```
 weaviate:
  command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
  image: semitechnologies/weaviate:1.17.1
  ports:
    - "8080:8080"
  restart: on-failure:0
  environment:
    QUERY_DEFAULTS_LIMIT: 25
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    DEFAULT_VECTORIZER_MODULE: 'none'
    ENABLE_MODULES: 'backup-filesystem'
    CLUSTER_HOSTNAME: 'vqWGpq84oJa0'
    LOG_LEVEL: debug
    GODEBUG: gctrace=1
    BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/weaviate_backups'
  volumes:
    - ./backup:/var/lib/weaviate/weaviate_backups
```
2. Restore the dataset [here](https://drive.google.com/file/d/1-GUYHRUuBNndVa0LMa1CBcgTPmsU1NBR/view?usp=share_link)
3. Run the attached notebook
[bug_limit_or.pdf](https://github.com/weaviate/weaviate/files/10517186/bug_limit_or.pdf)
