### ISSUE TITLE
Shards: Add node-affinity to shards and classes

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2586]
## Simple use case

* I have a few big classes and many small classes
* I don't want Weaviate to assign those to nodes in a round-robin fashion, but rather balance them according to their sizes
* For this, I'd like to be able to tell a class where it should end up (similar to Kubernetes node-affinity, anti-affinity, etc.)

## Advanced Case

* Instead of creating a new class, I want to move an existing class
* Note, this overlaps with #2228

**Comment by etiennedi** [comment]
## API Propsoal

```yaml
"shardingConfig": {
  "nodeAffinity": {
    "allowNodes": ["node1", "node3"],
    "disallowNodes": ["node2"],
  }
}
```

* The above class could schedule shards on `"node1"` and `"node3"`, but not on `"node2"`
* If neither allowed, nor disallowed nodes are specified, all nodes are allowed
* If only allowed nodes are specified, only the explicitly specified nodes are allowed
* If only disallowed nodes are specified, all nodes except the ones specified are allowed.
