### ISSUE TITLE
List existing indexes for a class

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#2652]
As a first step towards Reindexing (#2359, #2485) the first step is to list what indexes exist on a class. Currently indexes are implicit (they are controlled by specific props), but it's hard to understand which indexes actually exist for a given class.

Therefore the first step is to list indexes for a class, for example using 
```http
GET /v1/schema/{className}/indexes
```

which would return a list of all indexes, why they exist, possible stats, etc.

In a second step, this could then be extended to perform actions on a specific index, such as run a reindex process on select or all indexes.

**Comment by etiennedi** [comment]
API Draft:

```yaml
GET /v1/schema/MyClass/indexes

{
  "class": "MyClass",
  "shardCount": 2,
  "indexes": [{
    "id": "vector",
    "subject": "primary_vector",   # in the future there could be more than one
    "type": "hnsw",
    "reason": "Class was created with vectorIndexType=hnsw and vectorIndexConfig.skip=false",
    "paths": ["/shard1/hnsw", "shard2/hnsw"],
    "status": "ready"    # in the future could be unready due to ongoing reindexing.
  },{
    "id": "property_my_prop_1",
    "subject": "my_prop_1",
    "type": "roaringset", # good way to verify that roaring bitmaps are used
    "paths": ["/shard1/prop1", "shard2/prop1"],
     "status": "ready"    # in the future could be unready due to ongoing reindexing.
  }]
}
```

**Comment by etiennedi** [comment]
The next step would then be to add stats: mainly size on disk and size in memory per index.

**Comment by byronvoorbach** [comment]
> The next step would then be to add stats: mainly size on disk and size in memory per index.

I think this has the most value for us at CS. This feature would be great!

**Comment by etiennedi** [comment]
![image](https://user-images.githubusercontent.com/8974479/219901784-b7288924-e921-459c-8a78-703a00fd6622.png)

I've implemented an MVP with the version above and realized that just listing `paths` like in the draft above won't be very nice once we show more stats that are all shard-specific. We should probably explicitly list shards, something like:

```yaml

  "class": "MyClass",
  "shardCount": 2,
  "total": 2,
  "indexes": [{
    "id": "vector",
    "subject": "primary_vector",   # in the future there could also be property_vector
    "type": "hnsw",
    "reason": "Class was created with vectorIndexType=hnsw and vectorIndexConfig.skip=false", 
    "status": "ready"    # in the future could be unready due to ongoing reindexing.
    "shards": [{
      "id": "shard1",
      "path": "/shard1/vector",
      "size_on_disk_mb": 177.13,
      "size_in_memory_mb": 177.13,
    }, {
      # etc
    }]
  },{
    # ...
  }]
}
```
