### ISSUE TITLE
Index out of range error solved by removing one instance

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#2683]
I installed a GKE cluster with 2 replicas. Weaviate 1.17.4

After any update of the configuration (adding a module, upgrading from Weaviate 1.17.1 to 1.17.4), I get the following error:
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/1785759/221373636-6adbec7d-22a2-465a-87d3-34300adced7d.png">

But I discovered that if I remove the faulty instance weaviate-0, it is automatically recreated, and the cluster is working fine !!!

**Comment by etiennedi** [comment]
Thanks for the report, can you elaborate on how we can reproduce this exactly? 

Could you please also try if this still occurs with a Helm chart of version of [v15.3.1 or newer](https://github.com/weaviate/weaviate-helm/releases/tag/v15.3.1). This version fixed an issue where the cluster configuration would get out of sync depending on the state of healthy nodes. With just two nodes in the cluster, I could imagine that this bug could cause this issue.

**Comment by eostis** [comment]
(I will try with Chart v15.3.1)

I used Chart v15.2 with Weaviate v1.17.4

I just created the instance with:
```
replicas: 2

env:
  AUTOSCHEMA_ENABLED: false

modules:
  text2vec-openai:
    enabled: true

  text2vec-cohere:
    enabled: true

  qna-openai:
    enabled: true

```
Then updated the same values to activate a module:
```
replicas: 2

env:
  AUTOSCHEMA_ENABLED: false

modules:
  # Activation of CLIP (or other updates of the config) caused the issue
  multi2vec-clip:
    enabled: true

  text2vec-openai:
    enabled: true

  text2vec-cohere:
    enabled: true

  qna-openai:
    enabled: true
```
