### ISSUE TITLE
Inconsistent results in query using with_where in combination with with_limit.

### ISSUE THREAD

**Issue by cri-volo** [weaviate/weaviate#2686]
- Weaviate version 1.17.4
- Python client version 3.11.0

Good afternoon I'm currently indexing news in multi-language from different sources using the following schema:
```yaml
{
  "classes": [
    {
      "class": "Document",
      "description": "A document",
      "vectorIndexType": "hnsw",
      "vectorIndexConfig": {
        "distance": "cosine",
        "efConstruction": 128,
        "maxConnections": 64
      },
      "vectorizer": "text2vec-transformers",
      "moduleConfig": {
        "qna-openai": {
          "model": "text-davinci-002",
          "maxTokens": 16,
          "temperature": 0.0,
          "topP": 1,
          "frequencyPenalty": 0.0,
          "presencePenalty": 0.0
        }
      },
      "properties": [
        {
          "dataType": [
            "string"
          ],
          "description": "Internal Id of the document",
          "name": "data_hash",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Title of the article",
          "name": "title",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": false,
              "vectorizePropertyName": true
            }
          }
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "name": "content",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": false,
              "vectorizePropertyName": true
            }
          }
        },
        {
          "dataType": [
            "string"
          ],
          "description": "Language of the document",
          "name": "language",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        },
        {
          "dataType": [
            "date"
          ],
          "description": "date of the document",
          "name": "document_date",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        },
        {
          "dataType": [
            "string"
          ],
          "description": "headline of the document",
          "name": "headline_name",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        },
        {
          "dataType": [
            "string"
          ],
          "description": "country code of the document",
          "name": "country_code",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        },
        {
          "dataType": [
            "int"
          ],
          "description": "readership of the document",
          "name": "readership",
          "moduleConfig": {
            "text2vec-transformers": {
              "skip": true,
              "vectorizePropertyName": false
            }
          }
        }
      ],
      "replicationConfig": {
        "factor": 3
      }
    }
  ]
}

```

As text2vec-transformers I'm using sentence-transformers-paraphrase-multilingual-mpnet-base-v2.

This is an example of indexed document:

```
{
'content': "SugarCRM today announced Fern Energy, a leading company in the energy sector, ...
'document_date': '2023-02-21T17:21:00Z'
'headline_name': 'The Post and Mail'
'title': 'SugarCRM Powers Sales Automation for Fern Energy, Supercharges Customer Experience for the Energy Sector Worldwide'
'data_hash': '0CB22847568A107C813D9FC7210605F3C9E0040CA598A3FD59CBCE340DAFFEA2'
}
```

As title, when running a get function filtering for the date property and setting different values of _with_limit_, the code returns incosistent results.

Here's the python code used for the get request:

```python
weaviate.client.query.get("Document", ["title", "data_hash", "content", "headline_name", "document_date"])\
.with_where(
    {
    "path":["document_date"], 
    "operator":"LessThan", 
    "valueDate":"2023-02-24T00:00:00Z"
    }
)\
.with_limit(n)\
.do()
```

Without the _with_limit_ filter I get 25 results;
Setting the _with_limit_ filter equal to 10 returns no results
Setting the _with_limit_ filter equal to 200 returns 50 results

Thank you very much for the help!
