### ISSUE TITLE
dial tcp: lookup api.openai.com on * read udp

### ISSUE THREAD

**Issue by vegaviazhang** [weaviate/weaviate#2695]
Hi, Thanks For your excellent projects, I have met a ERROR 

# **When I use demo code, error appears**
### docker-compose content
```yaml
version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.17.5
    restart: on-failure:0
    ports:
     - "18090:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      CLUSTER_HOSTNAME: 'node1'

      #DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      #ENABLE_MODULES: text2vec-transformers
      #TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080

      # openai config
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
```

### demo code connect to weaviate
```python
import requests
import weaviate


# FIXME -> 0 create weaviate client
client = weaviate.Client(
    "http://192.168.99.100:18090",
    additional_headers={
        "X-OpenAI-Api-Key": "sk-this is my openai key"  # Replace with your API key
    }
)  # <== if you use Docker-compose

# FIXME -> 1 create schema-class
CLASS_NAME = "Question"
class_obj = {
    "class": f"{CLASS_NAME}",
    "vectorizer": "text2vec-openai",  # Or "text2vec-cohere" or "text2vec-huggingface"
    "description": "A description of this class, in this case, it is about publications",
}

# Load data
resp = requests.get('https://raw.githubusercontent.com/weaviate-tutorials/quickstart/main/data/jeopardy_tiny.json')
data = resp.json()

# FIXME -> 3 import_data
with client.batch as batch:  # Configure a batch process
    batch.batch_size = 100
    for i, d in enumerate(data[:1]):
        print(f"importing question: {i + 1}")
        properties = {
            "answer": d["Answer"],
            "question": d["Question"],
            "category": d["Category"],
        }
        client.batch.add_data_object(properties, "Question")
```

### Run the py file above, ERROR INFO appear.
* {'error': [{'message': 'update vector: send POST request: Post "https://api.openai.com/v1/embeddings": dial tcp: lookup api.openai.com on 127.0.0.11:53: read udp 127.0.0.1:39498->127.0.0.11:53: i/o timeout'}]}
