### ISSUE TITLE
Batch import timeouts after importing 650k docs 

### ISSUE THREAD

**Issue by vbanos** [weaviate/weaviate#2763]
Hello from the Internet Archive,
We try to batch import ~2M documents using the latest weaviate running via Docker.
Our documents have ~12 string/text attributes. One of them contains text extracted from PDF, the rest are fairly short strings.
After importing ~650k documents, we start getting the following error for all submissions.
```
Batch import failed The 'objects' creation was cancelled because it took longer than the configured timeout of 60s. Try reducing the batch size (currently 100) to a lower value. Aim to on average complete batch request within less than 10s
Progress 685200 2023-03-15 08:31:07.052322
``` 
Initially, we tried using batch size=500 and had the same issues. We reduce it to 100 and still get the same error.

In the past, we tried using weaviate with no modules and were able to import all documents without any issues.
Right now, we use the following configuration:
```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.0
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - /opt/weaviate/data:/var/lib/weaviate
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SUM_INFERENCE_API: 'http://sum-transformers:8080'
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      ENABLE_MODULES: 'text2vec-contextionary,qna-transformers,ner-transformers,sum-transformers,text-spellcheck,ref2vec-centroid'
      CLUSTER_HOSTNAME: 'node1'
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'true'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
    - 9999:9999
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '0'
  sum-transformers:
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '0'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
...
```
Our server is a VM with 30 cores, Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz, 43GB RAM. SSD disk. No GPU.

Questions:
1. I suspect that weaviate is becoming gradually slower as more data are added to the database because the enabled modules need to do some kind of processing. Is this true?
2. Is it possible to get some sense of the overhead of each module? I need to import orders of magnitude more data and it would be useful to know which module is causing the greatest delay.
3. Could we do some kind of optimisation? We just use `client.batch.configure(batch_size=100)` and `client.batch.add_data_object` in a loop.
Thank you
