### ISSUE TITLE
How can I  get all the data of field in Python-Client.

### ISSUE THREAD

**Issue by vegaviazhang** [weaviate/weaviate#2847]
**This is an exciting project, very outstanding. Thank you for your contributions to this project.**

**Hi, Is there a place where I can get help? I have two question about Query in Python-Client.**

**1. I want get all the data of field as follows: how can I use offset in Python-Client**
```python
response =  client.query.get("Document", ["pmid"]).with_limit(20000).do()
pmid_list = [item['pmid'] for item in response['data']['Get']["Document"]]
print(f"pmid_list: {len(pmid_list)}")
'''output
'explorer: list class: search: invalid pagination params: query maximum results exceeded'
'''
```

**2. If I don't init `ENABLE_MODULES=BACKUP_S3_PATH` in docker-compose.yml, but there are many data in weaviate, and how can I find the stored data. My docker-compose.yaml as follows:**
```yaml]
version: '3.4'
services:
  weaviate:
    #image: semitechnologies/weaviate:1.17.5
    image: semitechnologies/weaviate:latest
    restart: on-failure:0
    volumes:
      - ./vega_weaviate/weaviate:/var/lib/weaviate
    ports:
     - "18091:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      CLUSTER_HOSTNAME: 'node1'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai

```
