### ISSUE TITLE
docker-compose configurator returns only partial configuration files

### ISSUE THREAD

**Issue by ScripterSugar** [weaviate/weaviate#2897]
Hello! I've been trying to generate docker-compose file from weaviate documentation's docker-compose configurator https://weaviate.io/developers/weaviate/installation/docker-compose#configurator

It gives me URL like this: `https://configuration.weaviate.io/v2/docker-compose/docker-compose.yml?generative_openai=false&media_type=text&modules=modules&ner_module=false&openai_key_approval=yes&qna_module=false&ref2vec_centroid=false&runtime=docker-compose&spellcheck_module=false&sum_module=false&text_module=text2vec-openai&weaviate_version=v1.18.3`

and the contents of that file is

```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.3
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: $OPENAI_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
...
```

That starting `---` and ending `...` is not written by myself, above itself as a whole is content of configuration file URL.

it seems like the URL's returning partial configuration only.

Am I doing something wrong, or is the configurator broken at the moment?
