### ISSUE TITLE
Query search with where limit is slow

### ISSUE THREAD

**Issue by baaazik** [weaviate/weaviate#2980]
**Short  summary**
I have a news documents with datetime property. I try to filter document by the specific date range and requests contains such filter conditions are extremely slow taking over 1 second regardless query documents limit. Filter query looks like `(datetime >= X) AND (datetime < Y)`. 

Are there any methods to speed-up such queries?

**Details:**

I run Weaviate on a regular consumer desktop.
Scheme contains one class. Vector index is enabled only for "title" property and inverted index is enabled only for "datetime" property. There are ~650k documents in database.
```
{
    "classes": [
        {
            "class": "News2",
            "invertedIndexConfig": {
                "bm25": {
                    "b": 0.75,
                    "k1": 1.2
                },
                "cleanupIntervalSeconds": 60,
                "stopwords": {
                    "additions": null,
                    "preset": "en",
                    "removals": null
                }
            },
            "moduleConfig": {
                "text2vec-transformers": {
                    "poolingStrategy": "masked_mean",
                    "vectorizeClassName": false
                }
            },
            "properties": [
                {
                    "dataType": [
                        "int"
                    ],
                    "indexInverted": false,
                    "moduleConfig": {
                        "text2vec-transformers": {
                            "skip": true,
                            "vectorizePropertyName": false
                        }
                    },
                    "name": "index"
                },
                {
                    "dataType": [
                        "int"
                    ],
                    "indexInverted": true,
                    "moduleConfig": {
                        "text2vec-transformers": {
                            "skip": true,
                            "vectorizePropertyName": false
                        }
                    },
                    "name": "datetime"
                },
                {
                    "dataType": [
                        "string"
                    ],
                    "indexInverted": false,
                    "moduleConfig": {
                        "text2vec-transformers": {
                            "skip": false,
                            "vectorizePropertyName": false
                        }
                    },
                    "name": "title",
                    "tokenization": "word"
                }
            ],
            "replicationConfig": {
                "factor": 1
            },
            "shardingConfig": {
                "virtualPerPhysical": 128,
                "desiredCount": 1,
                "actualCount": 1,
                "desiredVirtualCount": 128,
                "actualVirtualCount": 128,
                "key": "_id",
                "strategy": "hash",
                "function": "murmur3"
            },
            "vectorIndexConfig": {
                "skip": false,
                "cleanupIntervalSeconds": 300,
                "maxConnections": 64,
                "efConstruction": 128,
                "ef": -1,
                "dynamicEfMin": 100,
                "dynamicEfMax": 500,
                "dynamicEfFactor": 8,
                "vectorCacheMaxObjects": 1000000000000,
                "flatSearchCutoff": 40000,
                "distance": "cosine"
            },
            "vectorIndexType": "hnsw",
            "vectorizer": "text2vec-transformers"
        }
    ]
}
```

Query without date limit takes few milliseconds, e.g.
```
{
  Get {
    News2(limit: 10) {
      index, title, datetime
    }
  }
}
```
Query with filter `datetime > X` or `datetime < X` takes few milliseconds too.
```
{
  Get {
    News2(
        limit: 10,
        where: {
            path: ["datetime"],
            operator: LessThan,
            valueInt: 1583006400,
        }) {
      index, title, datetime
    }
  }
}
```

But when I tried to get news for specific date range like `(datetime >= X) AND (datetime < Y)` the request takes over 1 seconds.
There are 1443 documents match this query, but only 10 is returned accordint to the limit.
```
{
  Get {
    News2(
        limit: 10,
        where: {
            operator: And,
            operands: [
            {
                path: ["datetime"],
                operator: LessThan,
                valueInt: 1583092800
            }, {
                path: ["datetime"],
                operator: GreaterThanEqual,
                valueInt: 1583006400
            },],
        }) {
      index, title, datetime
    }
  }
}
```

My docker compose file:
```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.17.2
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      GOMEMLIMIT: 20GiB
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      QUERY_MAXIMUM_RESULTS: 100000
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - 'gpu'
...
```

However, same query in SQLite is executing almost instantly. It takes... too small time to measure to get 10 records and ~0.1s to get (and print) all 1443 records.
```
.timer on
SELECT * FROM rss_news WHERE publ_date BETWEEN "2020-03-01" AND "2020-03-02" LIMIT 10;
Run Time: real 0.000 user 0.000212 sys 0.000000

SELECT * FROM rss_news WHERE publ_date BETWEEN "2020-03-01" AND "2020-03-02" LIMIT 10;
Run Time: real 0.115 user 0.007837 sys 0.000000
```

Are the any methods to speed-up Weaviate query filtering?
