### ISSUE TITLE
Weaviate server not working with SSL

### ISSUE THREAD

**Issue by adem-mb** [weaviate/weaviate#2994]
I am trying to setup Weaviate with HTTPS. I want to note that I did not find the HTTPS configuration steps in the documentation. Also, the configuration in the website does not give you the option to use HTTPS it gives you the docker-compose file with HTTP and it works fine with HTTP. 
To use HTTPS I read the log and configured docker-compose file based on the error messages.
I am using the following config in docker-compose, 
```
weaviate:
  command:
    - --host
    - 0.0.0.0
    - --port
    - '28080'
    - --scheme
    - https
    - --tls-certificate
    - '/home/certificate.crt'
    - --tls-key
    - '/home/private.key'
  image: semitechnologies/weaviate:1.17.2
  ports:
    - "28080:28080"
  restart: on-failure
  environment:
    OPENAI_APIKEY: $OPENAI_TOKEN
    QUERY_DEFAULTS_LIMIT: 25
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
    ENABLE_MODULES: 'text2vec-openai'
    CLUSTER_HOSTNAME: 'node1'
    LOG_LEVEL: 'info'
  volumes:
    - weaviate-volume:/var/lib/weaviate
    - ./gitignored.d:/gitignored.d
    - ./weaviate-ssl:/home
```

The problem is I can't connect to weaviate the python client gives me this error :
```HTTPSConnectionPool(host='127.0.0.1', port=28080): Max retries exceeded with url: /v1/.well-known/openid-configuration (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))```

Am I missing something, I think this could be a bug.
