### ISSUE TITLE
Slice out of bounds recovering objects

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#2996]
Reference https://weaviate.slack.com/archives/C017EG2SL3H/p1683579170564039

```
> kubectl logs weaviate-659459fc5d-fpwzt -f
{"action":"config_load","config_file_path":"./weaviate.conf.json","level":"info","msg":"no config file specified, using default or environment based","time":"2023-05-09T03:20:13Z"}
{"action":"startup","default_vectorizer_module":"text2vec-openai","level":"info","msg":"the default vectorizer modules is set to \"text2vec-openai\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-05-09T03:20:13Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-05-09T03:20:13Z"}
{"action":"lsm_recover_from_active_wal","class":"Group","index":"group","level":"warning","msg":"active write-ahead-log found. Did weaviate crash prior to this? Trying to recover...","path":"/var/lib/weaviate/group_TXbhdZZC0iZi_lsm/objects/segment-1683602244233136259.wal","shard":"TXbhdZZC0iZi","time":"2023-05-09T03:20:14Z"}
{"action":"lsm_recover_from_active_wal_success","class":"Group","index":"group","level":"info","msg":"successfully recovered from write-ahead-log","path":"/var/lib/weaviate/group_TXbhdZZC0iZi_lsm/objects/segment-1683602244233136259.wal","shard":"TXbhdZZC0iZi","time":"2023-05-09T03:20:14Z"}
panic: runtime error: slice bounds out of range [:3456106500] with capacity 57943

goroutine 48 [running]:
github.com/weaviate/weaviate/usecases/byte_operations.(*ByteOperations).CopyBytesFromBuffer(...)
	/go/src/github.com/weaviate/weaviate/usecases/byte_operations/byte_operations.go:51
github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*DiskTree).readNode(0xffffffffffffff9c?, {0x7f9f90303d98?, 0x40f67f?, 0x0?})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/disk_tree.go:105 +0x49b
github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*DiskTree).AllKeys(0xc0003ee4c8)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/disk_tree.go:179 +0x9f
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segment).computeAndStoreBloomFilter(0xc0003fb860, {0xc00398c5b0, 0x65})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_bloom_filters.go:72 +0x3b
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segment).initBloomFilter(0xc0003fb860)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_bloom_filters.go:59 +0xc5
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegment({0xc00398c4d0, 0x62}, {0x1b41410?, 0xc0030c4150}, 0x0, 0x0?)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment.go:136 +0xa34
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegmentGroup({0xc0000454f0, 0x43}, 0xb2d05e00, {0x1b41410, 0xc0030c4150}, 0x0, 0x0, {0x175186b, 0xd}, 0x0)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group.go:120 +0x925
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.NewBucket({0x1b2e0e8, 0xc00004e048}, {0xc0000454f0, 0x43}, {0xc0000460a6, 0x11}, {0x1b41410?, 0xc0030c4150?}, 0x0, {0xc003070040, ...})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:118 +0x2d1
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Store).CreateOrLoadBucket(0xc002d63680, {0x1b2e0e8, 0xc00004e048}, {0xc003978020, 0x1a}, {0xc003070040, 0x3, 0x4})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/store.go:118 +0x128
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).addProperty(0xc003090d80, {0x1b2e0e8, 0xc00004e048}, 0xc002d62f00)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:550 +0x7a5
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initProperties.func1.1()
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_init_properties.go:49 +0x128
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa5
```

**Comment by ceseale** [comment]
Some extra info:

This is deployed in azure aks and this is the volume type I'm using:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-storage-claim
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 32Gi
```

Dockfile:
```
# Base image
FROM semitechnologies/weaviate:1.18.0

# Expose port
EXPOSE 8080

# Environment variables
ENV QUERY_DEFAULTS_LIMIT=20 \
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true \
    PROMETHEUS_MONITORING_ENABLED=false \
    PERSISTENCE_DATA_PATH=/var/lib/weaviate \
    ENABLE_MODULES=text2vec-openai \
    QUERY_MAXIMUM_RESULTS=100 \
    WEAVIATE_LOG_LEVEL=debug \
    CLUSTER_HOSTNAME=node1

# Command
CMD ["--host", "0.0.0.0", "--port", "8080", "--scheme", "http"]
```

**Comment by trengrj** [comment]
Hi @ceseale for the persistence volume claim is there a reason for the `ReadWriteMany` access mode? How many Weaviate replicas/pods are you running??

**Comment by cybye** [comment]
Same issues with azure files mounted in container instance. Working fine on host storage (ephemeral).

**Comment by pa-mc** [comment]
Same here... I had to revert to use SSD storage which is much more expensive

**Comment by eschbach-dd** [comment]
> Same here... I had to revert to use SSD storage which is much more expensive

How do you use SSD storage? Could you provide me an k8s yaml example for an pvc?

I have the same problem ._.

**Comment by pa-mc** [comment]
> > Same here... I had to revert to use SSD storage which is much more expensive
> 
> How do you use SSD storage? Could you provide me an k8s yaml example for an pvc?
> 
> I have the same problem ._.

Actually, I mispoke, well, I did temporarily switched to SSD Storage. But later I swtiched to use Azure Blob Storage. (I'm using AKS). Also, I'm using their official `weaviate helm chart`, and ArgoCD to sync to AKS. The following are the stuff I need to overwrite for my use case. 

```yaml
source:
  repoURL: 'https://weaviate.github.io/weaviate-helm'
  targetRevision: 16.2.0
  helm:
    parameters:
      - name: service.type
        value: ClusterIP
      - name: modules.default_vectorizer_module
        value: text2vec-openai
      - name: modules.text2vec-openai.apiKey
        value: yourOpenAIKey
      - name: modules.text2vec-openai.enabled
        value: 'true'
      - name: backups.azure.enabled
        value: 'true'
      - name: backups.filesystem.enabled
        value: 'true'
      - name: debug
        value: 'true'
      - name: env.PROMETHEUS_MONITORING_ENABLED
        value: 'true'
      - name: env.REINDEX_VECTOR_DIMENSIONS_AT_STARTUP
        value: 'true'
      - name: env.TRACK_VECTOR_DIMENSIONS
        value: 'true'
      - name: env.ENABLE_MODULES
        value: 'backup-azure,backup-filesystem'
      - name: env.AZURE_STORAGE_ACCOUNT
        value: yourAzureStorageAccount
      - name: backups.azure.envconfig.BACKUP_AZURE_CONTAINER
        value: yourAzureStorageAccountBlobContainer
      - name: modules.text2vec-cohere.enabled
        value: 'true'
      - name: modules.text2vec-huggingface.enabled
        value: 'true'
      - name: storage.size
        value: 500Gi
      - name: storage.storageClassName
        value: azureblob-nfs-premium
```

The important bit is. 

```
      - name: storage.size
        value: 500Gi
      - name: storage.storageClassName
        value: azureblob-nfs-premium
```

Hope this is helpful :)

**Comment by Timbot-42** [comment]
> Same issues with azure files mounted in container instance. Working fine on host storage (ephemeral). Maybe CIFS related?
edit: I was using 1 container with 1 instance and 1 object in database.

@cybye did you find a solution for deploying as a container in Azure with Azure Files/alternative storage? I am also hitting the same problem. Manage to import objects fine but when I start to query, first one or two work ok then I get the slice bounds error and then the container is in a constant crash/restart cycle. Using latest image as of today, assuming 1.19 or 1.20, and I am running in Azure Vnet if that makes a difference.

My latest logs

{"action":"startup","default_vectorizer_module":"text2vec-openai","level":"info","msg":"the default vectorizer modules is set to \"text2vec-openai\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-07-08T09:06:18Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-07-08T09:06:18Z"}
{"level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2023-07-08T09:06:19Z"}
{"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2023-07-08T09:06:19Z"}
{"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2023-07-08T09:06:19Z"}
{"action":"hnsw_vector_cache_prefill","count":1000,"index_id":"docchunk_nTApi7KuhtOz","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2023-07-08T09:14:06Z","took":170901}
panic: runtime error: slice bounds out of range [:892613738] with capacity 1411

goroutine 103 [running]:
github.com/weaviate/weaviate/usecases/byte_operations.(*ByteOperations).CopyBytesFromBuffer(...)
        /go/src/github.com/weaviate/weaviate/usecases/byte_operations/byte_operations.go:57
github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*DiskTree).readNode(0xffffffffffffff9c?, {0x7fb362a6dc44?, 0x153c5e0?, 0xc000272d88?})
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/disk_tree.go:105 +0x49b
github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*DiskTree).AllKeys(0xc002c7c108)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/disk_tree.go:179 +0x9f
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segment).computeAndStoreBloomFilter(0xc0026321a0, {0xc000534ae0, 0x5a})
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_bloom_filters.go:72 +0x3b
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segment).initBloomFilter(0xc0026321a0)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_bloom_filters.go:59 +0xc5
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegment({0xc0005349c0, 0x57}, {0x1c1f770?, 0xc0004b2700}, 0x0, 0x1?)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment.go:136 +0xa34
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*SegmentGroup).add(0xc00384a460, {0xc0005349c0, 0x57})
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group.go:162 +0xdf
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).atomicallyAddDiskSegmentAndRemoveFlushing(0xc0041041e0)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:857 +0xb5
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).FlushAndSwitch(0xc0041041e0)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:835 +0x1db
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).flushAndSwitchIfThresholdsMet(0xc0041041e0, 0xc0046212c0?)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:782 +0x197
github.com/weaviate/weaviate/entities/cyclemanager.(*multiCallbacks).execute(0xc0005d7530, 0xc002a44070)
        /go/src/github.com/weaviate/weaviate/entities/cyclemanager/callbacks.go:131 +0x265
github.com/weaviate/weaviate/entities/cyclemanager.(*cycleManager).Start.func1()
        /go/src/github.com/weaviate/weaviate/entities/cyclemanager/cyclemanager.go:87 +0x113
created by github.com/weaviate/weaviate/entities/cyclemanager.(*cycleManager).Start
        /go/src/github.com/weaviate/weaviate/entities/cyclemanager/cyclemanager.go:71 +0xa5

**Comment by StefanBogdan** [comment]
Hi @Timbot-42 , we are using a custom defined storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

And we reference this Storage class to Weaviate `managed-premium`.

Let me know if solves the problem?

@ceseale What SKU/type is the `azurefile-csi` Storage Class`?

We will investigate the NFS  types to understand what is going on.
