### ISSUE TITLE
Helm upgrade failing

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate#3021]
Upgrading from 1.16.0 to 1.19.1:
`UPGRADE FAILED: cannot patch "weaviate" with kind StatefulSet: StatefulSet.apps "weaviate" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`

The error does not mention which statefulset field has been changed in the newest release...

(Related to #2556 )

**Comment by antas-marcin** [comment]
Which version of Helm are you using? the latest version is [v16.3.0](https://github.com/weaviate/weaviate-helm/releases/tag/v16.3.0)

**Comment by eostis** [comment]
I'm using chart v16.3.0.

**Comment by eostis** [comment]
My script:

```
#!/bin/bash

# Set the Weaviate chart version
export CHART_VERSION="v16.3.0"
# Download the Weaviate Helm chart
wget -O downloads/weaviate.tgz https://github.com/semi-technologies/weaviate-helm/releases/download/$CHART_VERSION/weaviate.tgz
# Download an example values.yml (with the default configuration)
wget -O downloads/values.yaml https://raw.githubusercontent.com/semi-technologies/weaviate-helm/$CHART_VERSION/weaviate/values.yaml

######################### GCloud login ################################
gcloud container clusters get-credentials weaviate-1 --region europe-west1 --project weaviate-374814
######################### GCloud login ################################

# set the desired Weaviate version
export WEAVIATE_VERSION="1.19.4"

# set the desired namespace
export K8S_NAMESPACE="wpsolr-prod"

# Deploy
helm upgrade \
  "weaviate" \
  downloads/weaviate.tgz \
  --install \
  --namespace "$K8S_NAMESPACE" \
  --create-namespace \
  --values downloads/values.yaml \
  --values values-wpsolr-prod.yaml \
  --set "image.tag=$WEAVIATE_VERSION"

```

My values-wpsolr-prod.yaml, to add the text2vec-palm (in comments right now)
```
replicas: 2

env:
  AUTOSCHEMA_ENABLED: false

modules:
  text2vec-openai:
    enabled: true

  text2vec-cohere:
    enabled: true

  multi2vec-clip:
    enabled: true

  qna-openai:
    enabled: true

#  text2vec-palm:
#    enabled: false

```

**Comment by eostis** [comment]
No changes in values, no.

Previous versions:
- chart v15.2.0
- weaviate 1.17.4

**Comment by eostis** [comment]
(I copied my script and values above; the only changes where the chart and Weaviate versions)

**Comment by eostis** [comment]
@antas-marcin Thanks you so much.

There are good news and bad news ...

Good news:
It worked and upgraded the Weaviate cluster to 1.19.4, with the new PalM vectorizer. And I could index my WooCommerce demo: 

Bad news:
All demos on the cluster exhibit errors, even after reindexing:

`Fatal error: Uncaught Exception: Error sent from Weaviate: interface conversion: interface {} is *neartext.NearTextParams, not *neartext.NearTextParams (types from different packages)`

`
Fatal error: Uncaught Exception: Error sent from Weaviate: shard CjNNLx4jAn4q: unexpected status code 500 (shard proddemo2kopenai_CjNNLx4jAn4q: identify groups: hybrid search: dense search: aggregate grouped dense search: vector lengths don't match: 1536 vs 512`

It looks like the storage is corrupted after the upgrade.

**Comment by eostis** [comment]
@antas-marcin I downgraded to Weaviate 1.19.0, and I could index.

It looks like v1.19.4 has major issues !

**Comment by antas-marcin** [comment]
@eostis which modules do you have enabled?

**Comment by eostis** [comment]
@antas-marcin 

```
modules:
  text2vec-openai:
    enabled: true

  text2vec-cohere:
    enabled: true

  multi2vec-clip:
    enabled: true

  qna-openai:
    enabled: true

#  text2vec-palm:
#    enabled: false

```
