### ISSUE TITLE
YML Configurator Error

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate#3026]
This is my error:
```

weaviate_1          | {"action":"startup","default_vectorizer_module":"text2vec-transformers","level":"info","msg":"the default vectorizer modules is set to \"text2vec-transformers\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-05-16T03:03:26Z"}
weaviate_1          | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-05-16T03:03:26Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:27Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:28Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:29Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:30Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:31Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:32Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": dial tcp 172.18.0.2:8080: connect: connection refused","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:33Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:34Z"}
weaviate_1          | {"action":"transformer_remote_wait_for_startup","error":"send check ready request: Get \"http://t2v-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"transformer remote inference service not ready","time":"2023-05-16T03:03:36Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:38Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:39Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:40Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:41Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:42Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:43Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:44Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:45Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:46Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:47Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:48Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:49Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:50Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:51Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:52Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:53Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:54Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:55Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:56Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:57Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:58Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:03:59Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": context deadline exceeded","level":"warning","msg":"ner remote service not ready","time":"2023-05-16T03:04:00Z"}
```

Using a AMD64, 50Gb ssd, 2Gb Ram.
(let me know what I should type in to get any necessary info)

Docker URL
`curl -o docker-compose.yml "https://configuration.weaviate.io/v2/docker-compose/docker-compose.yml?generative_cohere=false&generative_openai=false&generative_palm=false&gpu_support=false&media_type=text&modules=modules&ner_module=true&ner_module_model=dbmdz-bert-large-cased-finetuned-conll03-english&qna_module=false&ref2vec_centroid=false&runtime=docker-compose&spellcheck_module=true&spellcheck_module_model=pyspellchecker-en&sum_module=false&text_module=text2vec-transformers&transformers_model=sentence-transformers-multi-qa-MiniLM-L6-cos-v1&weaviate_version=v1.19.3"`

And I added a volume when I ran it:
```

---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.3
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
      - /var/data-weaviate:/var/lib/weaviate
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,ner-transformers,text-spellcheck'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '0'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en

```
