### ISSUE TITLE
Bug: could not find the word in the contextionary

### ISSUE THREAD

**Issue by paralin** [weaviate/weaviate#3071]
Using weaviate commit 58713c9700e58c658cb0f4c578a8b516c9fc3e38 and contextionary commit 327ffb5f74ff9ede347bd31a8973d79d25fcac9b using docker images built from those commits:

The following yaml for docker-compose:

```yaml
version: '3.4'
services:
  weaviate:
    image: weaviate/weaviate:local
    ports:
      - 127.0.0.1:42069:8080
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      ENABLE_MODULES: 'text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-local
```

When using with a basic llama_index weaviate script:

```
import weaviate
from llama_index.vector_stores import WeaviateVectorStore

WEAVIATE_URL = "http://127.0.0.1:42069"
client = weaviate.Client(
    url=WEAVIATE_URL,
    additional_headers={"X-OpenAI-Api-Key": os.environ["OPENAI_API_KEY"]},
)

vector_store = WeaviateVectorStore(weaviate_client=client)
```

I get the following error:

```
UnexpectedStatusCodeException: Create class! Unexpected status code: 422, with response body: {'error': [{'message': "module 'text2vec-contextionary': invalid class name: could not find the word '_' from the class name 'Gpt_Index_408782758433177836_Node' in the contextionary"}]}.
```

How can I fix this? Thanks!
