### ISSUE TITLE
databases on prometheus did not shown

### ISSUE THREAD

**Issue by oldthreefeng** [weaviate/weaviate#3474]
from this  https://weaviate.io/blog/monitoring-weaviate-in-production to deploy .

weaviate deploy by helm in kuberentes.   already set prometheus on. 

install weaviate 

```
helm repo add weaviate https://weaviate.github.io/weaviate-helm
export CHART_VERSION="16.5.0"
export WEAVIATE_VERSION="1.21.0"
helm upgrade \                                             
  "weaviate" \
  weaviate/weaviate \
  --version $CHART_VERSION \
  --install \
  --namespace "weaviate" \
  --create-namespace \
  --values ./values.yaml \
  --set "image.tag=$WEAVIATE_VERSION"
```
install scrape

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: weaviate 
  namespace: prometheus
  labels:
    app: weaviate-pod-monitor
    prometheus: gd
    release: ack-prometheus-operator
spec:
  selector:
    matchLabels:
      app: weaviate
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /metrics
    scheme: http
    port: metrics 
    interval: 15s
    scrapeTimeout: 2s
```
on prometheus :
<img width="1198" alt="image" src="https://github.com/weaviate/weaviate/assets/38313565/d8d66c13-a2e6-4c9b-bc7f-19f711cd61d0">

<img width="1467" alt="image" src="https://github.com/weaviate/weaviate/assets/38313565/785fd81a-f55b-4d01-8572-638e8ba95ef2">
but dont show the article grafana data. 

the data is missing.. 

like:   queries_durations_ms_count  , queries_durations_ms_bucket  dont have any data. 
<img width="1467" alt="image" src="https://github.com/weaviate/weaviate/assets/38313565/bba10284-8ffc-41c8-a919-9419ec3d3956">
