### ISSUE TITLE
AutoSchema gives the wrong defaults for shardingConfig when multiTenancy is enabled

### ISSUE THREAD

**Issue by Sam-Pewton** [weaviate/weaviate#3624]
# Context

I am creating a community client for Weaviate in Rust (https://github.com/Sam-Pewton/weaviate-community.rust/tree/main). It is still a work in progress, but I noticed a some weird behaviour in the AutoSchema generation when deserializing the HTTP request outputs into custom types. For completeness, this is the output I was getting when trying to deserialize:
```
Err(
    reqwest::Error {
        kind: Decode,
        source: Error("unknown variant ``, expected `_id`", line: 1, column: 402),
    },
)
```
Similar Err outputs could be seen when expecting to find `murmur3` and `strategy` in the appropriate keys whilst debugging.

As part of the debugging process, I dumped the serialized json to stdout before trying to parse to the custom type. Here I noticed that the values that should be in place of the defaults were incorrect. To further verify that there is a bug here, I also recreated the issue with curl. See the 'Reproduce' section for details on how to reproduce this bug without Rust.

I have searched the documentation thoroughly, but have been unable to find any reference to this being the expected behaviour when using AutoSchema. As many of the values in the shardingConfig are locked to a single option, this leads me to believe that it is a bug.

# Reproduce

To make sure that it wasn't a problem with my implementation for deserialization, I have been able to recreate this problem using curl. 

The docker-compose.yml file I am using to test is at the bottom of this bug report for more clarity on the environment I am running this in.

Below is an example curl command that will reproduce the bug output:
```bash
curl \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{
        "class": "ThisIsABug",
        "multiTenancyConfig": {
            "enabled": true
        }
    }' \
    http://localhost:8080/v1/schema/ | json_pp
```

And the output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   972  100   864  100   108  76063   9507 --:--:-- --:--:-- --:--:-- 88363
{
   "class" : "ThisIsABug",
   "invertedIndexConfig" : {
      "bm25" : {
         "b" : 0.75,
         "k1" : 1.2
      },
      "cleanupIntervalSeconds" : 60,
      "stopwords" : {
         "additions" : null,
         "preset" : "en",
         "removals" : null
      }
   },
   "multiTenancyConfig" : {
      "enabled" : true
   },
   "properties" : null,
   "replicationConfig" : {
      "factor" : 1
   },
   "shardingConfig" : {
      "actualCount" : 0,
      "actualVirtualCount" : 0,
      "desiredCount" : 0,
      "desiredVirtualCount" : 0,
      "function" : "",
      "key" : "",
      "strategy" : "",
      "virtualPerPhysical" : 0
   },
   "vectorIndexConfig" : {
      "cleanupIntervalSeconds" : 300,
      "distance" : "cosine",
      "dynamicEfFactor" : 8,
      "dynamicEfMax" : 500,
      "dynamicEfMin" : 100,
      "ef" : -1,
      "efConstruction" : 128,
      "flatSearchCutoff" : 40000,
      "maxConnections" : 64,
      "pq" : {
         "bitCompression" : false,
         "centroids" : 256,
         "enabled" : false,
         "encoder" : {
            "distribution" : "log-normal",
            "type" : "kmeans"
         },
         "segments" : 0,
         "trainingLimit" : 100000
      },
      "skip" : false,
      "vectorCacheMaxObjects" : 1000000000000
   },
   "vectorIndexType" : "hnsw",
   "vectorizer" : "none"
}
```

Note that the default values for the shardingConfig are incorrect. I have extracted these below to make it more clear:
```
...
   "shardingConfig" : {
      "actualCount" : 0,
      "actualVirtualCount" : 0,
      "desiredCount" : 0,
      "desiredVirtualCount" : 0,
      "function" : "",
      "key" : "",
      "strategy" : "",
      "virtualPerPhysical" : 0
   },
...
```

I have tested this both on versions 1.20.0 (when multi-tenancy was introduced), and 1.21.3. The AutoSchema generation of the shardingConfig is the same in both versions.

# Expected Output
If I explicitly set the multiTenancyConfig to false or omit it all together, then the shardingConfig generates the defaults as expected:
```
   "shardingConfig" : {
      "actualCount" : 1,
      "actualVirtualCount" : 128,
      "desiredCount" : 1,
      "desiredVirtualCount" : 128,
      "function" : "murmur3",
      "key" : "_id",
      "strategy" : "hash",
      "virtualPerPhysical" : 128
   },
```
This is true for both 1.20.0 and 1.21.3.

# docker-compose.yml
```yaml
---
version: '3.8'

networks:
  system-integration:
    name: system-integration

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.3
    container_name: 'weaviate'
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'weaviate1'
      LOG_LEVEL: 'debug'
    networks:
      - system-integration
...
```
