### ISSUE TITLE
[LSM Store] Make sure tombstones are removed when merging with the root segment

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#3650]
# Background

When dealing with cursors (see also #3648) deletes should not degrade performance. The assumption (needs to be verified) is that right now a delete will remove any payload, but the tombstone will stick around after a compaction. The original intention behind this was that we do not know if the tombstone refers to a key that was written earlier.

However, when we perform a compaction, we know if the left segment is the root segment. If this is true, it is impossible for the key to have occurred previously.

# Goal

* During a compaction,
* if the left segment is the root segment (and only then) 
* make sure that an element that is finally deleted (i.e. the most recent write in the right segment - or in the left segment if there is no reference in the right segment) 
* disappears from the resulting segment altogether.

### 
Example in pseudo-yaml:

```yaml
segment0:
  - key: a
    value: 1
  - key: b
    value: 2

segment1:
  - key: c
    value: 3
  - key: b
    tombstone: true
```

should result in the following if `segment0` was the root segment:

```yaml
segment0:
  - key: a
    value: 1
  - key: c
    value: 3
```

If it was not the root segment, it should result in: (This is currently the case for all compactions)

```yaml
segment0:
  - key: a
    value: 1
  - key: b
    tombstone: true
  - key: c
    value: 3
```
