### ISSUE TITLE
Weaviate Restart Loop (deleted node without a tombstone)

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate#3782]
```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.2
    restart: unless-stopped
    environment:
      ASYNC_INDEXING: 'true'
      CLUSTER_HOSTNAME: 'node1'
      LOG_LEVEL: 'debug'
      GOMEMLIMIT: '30000MiB'
      ENABLE_MODULES: 'text-spellcheck'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
```
The following log pretty much repeats verbatim constantly restarting. It seems oddly similar to https://github.com/weaviate/weaviate/issues/1900 However this happens automatically without any querying/adding etc.... If the issue is unrelated to the log perhaps lmk if I can provide any additional information.

```
root-weaviate-1  | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255581) without a tombstone, tombstone was added","node_id":4255581,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1  | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255628) without a tombstone, tombstone was added","node_id":4255628,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1  | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255644) without a tombstone, tombstone was added","node_id":4255644,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255750) without a tombstone, tombstone was added","node_id":4255750,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255776) without a tombstone, tombstone was added","node_id":4255776,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255831) without a tombstone, tombstone was added","node_id":4255831,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255884) without a tombstone, tombstone was added","node_id":4255884,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255895) without a tombstone, tombstone was added","node_id":4255895,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255948) without a tombstone, tombstone was added","node_id":4255948,"time":"2023-11-16T13:29:21Z"}
root-weaviate-1         | {"action":"attach_tombstone_to_deleted_node","level":"info","msg":"found a deleted node (4255978) without a tombstone, tombstone was added","node_id":4255978,"time":"2023-11-16T13:29:21Z"}
root-text-spellcheck-1  | INFO:     Started server process [7]
root-text-spellcheck-1  | INFO:     Waiting for application startup.
root-text-spellcheck-1  | INFO:     Application startup complete.
root-text-spellcheck-1  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
root-text-spellcheck-1  | INFO:     172.23.0.2:33634 - "GET /.well-known/ready HTTP/1.1" 204 No Content
```
