### ISSUE TITLE
S3 Backup Halts For Unknown Reason

### ISSUE THREAD

**Issue by diovisgood** [weaviate/weaviate#3946]
### How to reproduce this bug?

EC2 instance t2.micro is running the `weaviate:1.22.0` or `1.23.0` docker container with the following docker-compose configuration:

```
services:
  database:
    image: semitechnologies/weaviate:1.22.0
    container_name: project-name-database
    ports:
     - "8080:8080"
    restart: always
    volumes:
      - data:/data
      - database:/database
    env_file:
      - aws.env
    environment:
      CLUSTER_HOSTNAME: 'node1'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/database'
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "backup-s3,backup-filesystem"
      BACKUP_S3_BUCKET: "project-name"
      BACKUP_FILESYSTEM_PATH: /data
```

File aws.env:
```
AWS_DEFAULT_REGION='eu-central-1'
AWS_ACCESS_KEY_ID='XXXXXXXXXXXXXXXXXXXX'
AWS_SECRET_ACCESS_KEY='XXXXXXXXXXXXXXXXXXXXXXXXX'
```

This access key belong to IAM user, which has the following AWS policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::project-name"
            ]
        },
        {
            "Sid": "AllObjectActions",
            "Effect": "Allow",
            "Action": "s3:*Object",
            "Resource": [
                "arn:aws:s3:::project-name/*"
            ]
        }
    ]
}

```

Code to make backup:
```
import weaviate
client = weaviate.Client('http://localhost:8080')
result = client.backup.create(
    backup_id='weaviate-backup-2023-12-26',
    backend='s3',
    wait_for_completion=False,
)

```

### What is the expected behavior?

The backup is written into S3 bucket `project-name`

### What is the actual behavior?

Server running weaviate docker container halts, not reacting to any commands. So that I have to stop EC2 instance.

Only the folder `weaviate-backup-2023-12-26` is created in S3 bucket, with the file `backup-config.json`:

```
{"startedAt":"2023-12-25T18:01:30.07259704Z","completedAt":"0001-01-01T00:00:00Z","id":"weaviate-backup-2023-12-25","nodes":{"node1":{"classes":["Document","Fragment","Project","Summary"],"status":"","error":""}},"node_mapping":null,"status":"STARTED","version":"2.0","serverVersion":"1.22.2","error":""}
```

### Server Version

1.22.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
