### ISSUE TITLE
Cannot update stopwords of class

### ISSUE THREAD

**Issue by erikvullings** [weaviate/weaviate#4091]
### How to reproduce this bug?

Create a class Article and set the stopwords. Next, try to update the stopwords using curl, following the [example in the docs](https://weaviate.io/developers/weaviate/api/rest/schema#example-request-for-updating-a-collection). It fails.

```js
{
  class: 'Article',
  description:
    'An article.',
  vectorizer: 'ref2vec-centroid',
  vectorIndexConfig: {
    vectorCacheMaxObjects: 150000000000,
    ef: 64,
    efConstruction: 128,
    maxConnections: 32,
  },
  moduleConfig: {
    'ref2vec-centroid': {
      referenceProperties: [hasFragments],
      method: 'mean',
    },
  },
  invertedIndexConfig: {
    cleanupIntervalSeconds: 60,
    stopwords: {
      preset: 'en',
      additions: [
  'aan',
  'aangaande',
  'aangezien',
  'achte',
  'achter',
  'achterna',
  'af']
    },
  },
  properties: [
    {
      dataType: ['text'],
      tokenization: 'word',
      description: 'ID of the feed, is a GUID',
      name: 'text',
      indexInverted: true,
    },
    ...
   ]
}
```

```bash
curl \
    -X PUT \
    -H "Content-Type: application/json" \
    -d '{
        "class": "Article",
        "invertedIndexConfig": {
            "stopwords": {
                "preset": "en",
                "additions": []
            }
        }
    }' http://localhost:8888/v1/schema/Article
```

### What is the expected behavior?

Stopwords are updated

### What is the actual behavior?

```json
{"error":[{"message":"vectorizer is immutable: attempted change from \"ref2vec-centroid\" to \"text2vec-transformers\""}]}
```

### Supporting information

I'm using the Docker setup, and tested it with weaviate v1.23.5 and 1.23.2.

``` yaml
weaviate:
    image: semitechnologies/weaviate:1.23.5
    restart: always
    networks:
      - my_network
    ports:
      - ${WEAVIATE_PORT}:8080
    depends_on:
      - t2v
      - i2v
      - reverse-proxy
    volumes:
      - weaviate3:/var/lib/weaviate
      - ./tmp/weaviate:/tmp/weaviate # Matches BACKUP_FILESYSTEM_PATH below
    environment:
      LOG_LEVEL: trace
      QUERY_DEFAULTS_LIMIT: 25
      ASYNC_INDEXING: "true"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      BACKUP_FILESYSTEM_PATH: /tmp/weaviate
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://reverse-proxy:80/t2v
      IMAGE_INFERENCE_API: http://reverse-proxy:80/i2v
      ENABLE_MODULES: "ref2vec-centroid,backup-filesystem,text2vec-transformers,img2vec-neural"
      # Map backup filesystem path to volume if you want to access it outside the container
      CLUSTER_HOSTNAME: node1
      AUTOSCHEMA_ENABLED: "false"
```

### Server Version

1.23.5

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
