### ISSUE TITLE
Concurrent schema operations can lead to deadlock

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4312]
### 3-node cluster
Spin up a 3-node cluster with this `docker-compose.yml`:
```yaml
version: '3.4'
services:
  weaviate-0:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-0
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2
  weaviate-1:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8081:8080
    - 50052:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-1
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2
  weaviate-2:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.10
    ports:
    - 8082:8080
    - 50053:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: '25'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: weaviate-2
      CLUSTER_JOIN: weaviate-0,weaviate-1,weaviate-2

```

You can spin it up like so:

```sh
docker compose -f docker-compos.yml down --remove-orphans
for i in {0..2}; do docker compose -f docker-compose.yml up -d weaviate-$i; sleep 5; done
```

### A chaotic script

Run the following script to induce chaos in the cluster:
```python
import multiprocessing
import weaviate
import weaviate.classes as wvc
import random, string
import warnings
import numpy as np
import time

warnings.filterwarnings("ignore", category=ResourceWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)


num_servers = 3


def run(worker_id: int):
    # send all the class delete/create to the same node
    client = weaviate.connect_to_local(port=8080, grpc_port=50051)
    client = weaviate.connect_to_local()
    client.collections.delete_all()
    client.collections.create(
        "MT",
        multi_tenancy_config=wvc.config.Configure.multi_tenancy(enabled=True),
        vector_index_config=wvc.config.Configure.VectorIndex.flat(),
    )
    client.close()

    # send all the tenant operations to any node
    port = 8080 + worker_id % num_servers
    grpc_port = 50051 + worker_id % num_servers

    client = weaviate.connect_to_local(port=port, grpc_port=grpc_port)

    tenants = [
        wvc.tenants.Tenant(
            name=f"t_{''.join(random.choices(string.ascii_lowercase, k=10))}"
        )
        for i in range(50)
    ]

    try:
        col = client.collections.get("MT")
        start = time.time()
        col.tenants.create(tenants)
        took = time.time() - start
        print(f"created tenant batch in {took:.2f}")

        with client.batch.fixed_size(50, 4) as batch:
            for tenant in tenants:
                for j in range(10):
                    batch.add_object(
                        "MT",
                        vector=np.random.rand(1, 1536)[0].tolist(),
                        tenant=tenant,
                    )
        failed = client.batch.failed_objects
        if len(failed) > 0:
            print(f"have {len(failed)} failures")
    except Exception as e:
        print(f"Error: {e}")
        # if "concurrent" in str(e):
        #     time.sleep(0.1)


def run_in_parallel():
    args = range(50)

    with multiprocessing.Pool() as pool:
        results = pool.map(run, args)


if __name__ == "__main__":
    run_in_parallel()
```

### What is the expected behavior?

It is completely expected that the chaos script shows lots of errors, it does operations that aren't compatible (such as deleting a class while adding tenants into that same class from another thread. However, what we don't expect to see is nodes dead-locking. I should be able to query e.g. the schema-status endpoint just fine:

```
for port in {8080..8082}; do curl -m 3 localhost:$port/v1/schema/cluster-status; done
{"healthy":true,"hostname":"weaviate-0","ignoreSchemaSync":false,"nodeCount":3}
{"healthy":true,"hostname":"weaviate-1","ignoreSchemaSync":false,"nodeCount":3}
{"healthy":true,"hostname":"weaviate-2","ignoreSchemaSync":false,"nodeCount":3}
```

### What is the actual behavior?

```
for port in {8080..8082}; do curl -m 3 localhost:$port/v1/schema/cluster-status; done
curl: (28) Operation timed out after 3002 milliseconds with 0 bytes received
curl: (28) Operation timed out after 3005 milliseconds with 0 bytes received
curl: (28) Operation timed out after 3003 milliseconds with 0 bytes received
```

At least two of three, often all three nodes, time out to schema requests. Note that my initial analysis showed that typically only one node is actually dead-locked. The rest is just cascading failures because the nodes try to contact the deadlocked node which can't respond.

### Server Version

`v1.23.10`, should affect all recent versions from at least `v1.19` on

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
