### ISSUE TITLE
3 node cluster issues  

### ISSUE THREAD

**Issue by phlegx** [weaviate/weaviate#5143]
### How to reproduce this bug?

Install Weaviate version `1.25.2`  with Helm chart  `17.0.0` on a three node Kubernetes cluster using the  yaml config attached

Use replication_factor 3 and consistency_level ALL and create some classes and objects which should work fine.

Shut down one node

Try to fetch object list like this (it will sometimes work, sometimes not):

`curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" "http://weaviate.weaviate.svc.cluster.local/v1/objects"`

Then Into one of the classes add a new test object:

```
curl -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" -X POST "http://weaviate.weaviate.svc.cluster.local/v1/objects" \
-H "Content-Type: application/json" \
  -d '{
    "class": "TokenStatistic__fca5b0b9_61c4_4371_a22a_ee6696d77d89",
    "properties": {
        "testProperty": "testValue"
    }
}'
```

Bring up the third node again and read out the object:

`curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" "http://weaviate.weaviate.svc.cluster.local/v1/objects/TokenStatistic__fca5b0b9_61c4_4371_a22a_ee6696d77d89/b8b824df-e341-58a0-8a91-2eed4549639d?consistency_level=QUORUM"`

Read the object from the node that was down explicitly (Which works)

`curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" "http://10.42.248.8:8080/v1/objects/TokenStatistic__fca5b0b9_61c4_4371_a22a_ee6696d77d89/b8b824df-e341-58a0-8a91-2eed4549639d?consistency_level=QUORUM"`

Get all Objects from that very class back (sometimes works, sometimes not. means  sometimes it will show the added object, sometimes not)

```
curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" "http://weaviate.weaviate.svc.cluster.local/v1/objects?class=TokenStatistic__fca5b0b9_61c4_4371_a22a_ee6696d77d89&consistency_level=ALL" | jq -r '
  if .error then
    .error[0].message
  else
    .objects[]
  end
'
```

Get all Objects from that very class back  from the node that was down  explicitly (never works)

```
curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $AUTHENTICATION_APIKEY_ALLOWED_KEYS" "http://10.42.248.8:8080/v1/objects?class=TokenStatistic__fca5b0b9_61c4_4371_a22a_ee6696d77d89&consistency_level=QUORUM" | jq -r '
  if .error then
    .error[0].message
  else
    .objects[]
  end
'
```

So we are not sure now if the object was really added to the node that was down again.

### What is the expected behavior?

The expected behavior would actually be that:

- Fetching the object list should always work, even if one node out of 3 is down
- Showing  all the objects of a class should show us the object that was added during the time one node is down once all nodes are back.

### What is the actual behavior?

- Fetching the object list does only sometimes work when 1 node out of 3 is down
- Showing  all the objects of a class  only sometimes work when 1 node out of 3 was down and cluster is up again to 3 nodes. If we fetch all the objects of a class directly from the node that was down, the object that was added is missing.

### Supporting information

```
backups:
  s3:
    enabled: true
    envconfig:
      BACKUP_S3_BUCKET: 29872348-weaviate-backups
      AWS_REGION: eu-central-1

authentication:
  anonymous_access:
    enabled: false
  oidc:
    enabled: false

authorization:
  admin_list:
    enabled: false
    users:
    %{~ for user in admin_users ~}
    - ${user}
    %{ endfor }
    read_only_users:
    %{~ for user in readonly_users ~}
    - ${user}
    %{ endfor }


initContainers:
  sysctlInitContainer:
    enabled: true
    sysctVmMaxMapCount: 524288

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: deploy/weaviate
          operator: In
          values:
          - "true"

env:
  AUTHENTICATION_APIKEY_ENABLED: 'true'

  # Expose metrics on port 2112 for Prometheus to scrape
  PROMETHEUS_MONITORING_ENABLED: true

  LOG_LEVEL: info

envSecrets:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: weaviate

service:
  type: ClusterIP

grpcService:
  enabled: false

resources:
  requests:
    cpu: 1m
    memory: 100Mi
  limits:
    memory: ${memory}Gi

annotations:
  ad.datadoghq.com/weaviate.checks: |
    {
      "weaviate": {
        "init_config": {},
        "instances": [
          {
            "openmetrics_endpoint": "http://%%host%%:2112/metrics",
            "weaviate_api_endpoint": "http://%%host%%:8080",
            "headers": {"Authorization": "Bearer ${api_key}"}
          }
        ]
      }
    }
```

### Server Version

1.25.2

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
