### ISSUE TITLE
"could not open cloud meta store" error during Weaviate Startup using one node

### ISSUE THREAD

**Issue by andrewisplinghoff** [weaviate/weaviate#5362]
### How to reproduce this bug?

Exact way of reproduction is unclear unfortunately. I have the impression that you need some amount of data in the database for this to occur, in our case 1-2M objects / 15 GB.

In general this error happens during startup of Weaviate, but not always (race condition?), and we had the impression that the error happened more often as we added more data to the database.

Server Setup Information
- Weaviate Server Version: 1.25.7
- Deployment Method: k8s using Helm
- Multi Node? Number of Running Nodes: 1
- Multitenancy?: no

### What is the expected behavior?

Weaviate should start up without errors. When using only one node, I would Weaviate not expect to try to find other nodes (RAFT_BOOTSTRAP_EXPECT is set to 1)

### What is the actual behavior?

Weaviate startup fails sometimes with the error message "could not open cloud meta store" and seemingly is unsuccessfully trying to find other nodes.

Bootstrap related logs:
```
{"action":"bootstrap","error":"could not join a cluster from [10.130.37.168:8300]","level":"warning","msg":"failed to join cluster, will notify next if voter","servers":["10.130.37.168:8300"],"time":"2024-07-01T11:06:49Z","voter":true}
{"action":"bootstrap","candidates":[{"Suffrage":0,"ID":"weaviate-0","Address":"10.130.37.168:8300"}],"level":"info","msg":"starting cluster bootstrapping","time":"2024-07-01T11:06:49Z"}
{"action":"bootstrap","error":"bootstrap only works on new clusters","level":"error","msg":"could not bootstrapping cluster","time":"2024-07-01T11:06:49Z"}
{"action":"bootstrap","level":"info","msg":"notified peers this node is ready to join as voter","servers":["10.130.37.168:8300"],"time":"2024-07-01T11:06:49Z"}
{"action":"bootstrap","error":"could not join a cluster from [10.130.37.168:8300]","level":"warning","msg":"failed to join cluster, will notify next if voter","servers":["10.130.37.168:8300"],"time":"2024-07-01T11:08:18Z","voter":true}
{"action":"bootstrap","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"error","msg":"notify all peers","servers":["10.130.37.168:8300"],"time":"2024-07-01T11:08:18Z"}
{"action":"startup","error":"bootstrap: context deadline exceeded","level":"fatal","msg":"could not open cloud meta store","time":"2024-07-01T11:08:18Z"}
```

### Supporting information

Environment variables of the StatefulSet:

```
- name: AUTHENTICATION_APIKEY_ENABLED
  value: 'true'
- name: AUTHENTICATION_APIKEY_USERS
  value: 'api-key-user-readOnly,api-key-user-admin'
- name: AUTHORIZATION_ADMINLIST_ENABLED
  value: 'true'
- name: AUTHORIZATION_ADMINLIST_READONLY_USERS
  value: api-key-user-readOnly
- name: AUTHORIZATION_ADMINLIST_USERS
  value: api-key-user-admin
- name: AUTOSCHEMA_ENABLED
  value: 'false'
- name: CLUSTER_DATA_BIND_PORT
  value: '7001'
- name: CLUSTER_GOSSIP_BIND_PORT
  value: '7000'
- name: DISABLE_TELEMETRY
  value: 'true'
- name: GOGC
  value: '100'
- name: LIMIT_RESOURCES
  value: 'true'
- name: LOG_LEVEL
  value: debug
- name: PROMETHEUS_MONITORING_ENABLED
  value: 'true'
- name: PROMETHEUS_MONITORING_GROUP
  value: 'false'
- name: PROMETHEUS_MONITORING_PORT
  value: '9091'
- name: QUERY_MAXIMUM_RESULTS
  value: '100000'
- name: REINDEX_VECTOR_DIMENSIONS_AT_STARTUP
  value: 'false'
- name: TIKTOKEN_CACHE_DIR
  value: /weaviate-backups/tiktoken_cache
- name: TRACK_VECTOR_DIMENSIONS
  value: 'false'
- name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
  valueFrom:
    secretKeyRef:
      name: weaviate-api-keys
      key: AUTHENTICATION_APIKEY_ALLOWED_KEYS
- name: CLUSTER_BASIC_AUTH_USERNAME
  valueFrom:
    secretKeyRef:
      name: weaviate-cluster-api-basic-auth
      key: username
- name: CLUSTER_BASIC_AUTH_PASSWORD
  valueFrom:
    secretKeyRef:
      name: weaviate-cluster-api-basic-auth
      key: password
- name: STANDALONE_MODE
  value: 'true'
- name: PERSISTENCE_DATA_PATH
  value: /var/lib/weaviate
- name: DEFAULT_VECTORIZER_MODULE
  value: none
- name: ENABLE_MODULES
  value: 'text2vec-openai,backup-filesystem'
```

### Server Version

1.25.7

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
