### ISSUE TITLE
generate.near_text fails if AWS credentials are passed as headers

### ISSUE THREAD

**Issue by MatthiasDurivet** [weaviate/weaviate#5457]
### How to reproduce this bug?

I am running `cr.weaviate.io/semitechnologies/weaviate:1.24.8` locally with docker compose
I am using the python SDK `weaviate-client==4.7.0`
I've enabled the following modules in docker compose: `ENABLE_MODULES: 'text2vec-aws,generative-aws'`
I'm specifying a `vectorizer_config` and `generative_config` like so:

```python
vectorizer_config = wvc.config.Configure.Vectorizer.text2vec_aws(
    region="eu-west-3",
    service="bedrock",
    model="cohere.embed-multilingual-v3",
)

generative_config = wvc.config.Configure.Generative.aws(
    region="eu-west-3",
    service="bedrock",
    model="amazon.titan-text-express-v1",
)

client.collections.create(
    name=name,
    vectorizer_config=vectorizer_config,
    generative_config=generative_config,
)
```

According to the official documentation, you need to pass the AWS credentials as headers:
https://weaviate.io/developers/weaviate/model-providers/aws/embeddings#api-credentials
```python
dotenv.load_dotenv()
aws_access_key = os.getenv("AWS_ACCESS_KEY")
aws_secret_key = os.getenv("AWS_SECRET_KEY")
headers = {
    "X-AWS-Access-Key": aws_access_key,
    "X-AWS-Secret-Key": aws_secret_key,
}

client = weaviate.connect_to_wcs(
    cluster_url=weaviate_url,                       # `weaviate_url`: your Weaviate URL
    auth_credentials=AuthApiKey(weaviate_key),      # `weaviate_key`: your Weaviate API key
    headers=headers
)
```

I've created a brand new AWS user "weaviate" and placed it's security credentials in the headers.
I am using a `.env` file with python's `dotenv.load_dotenv()` to achieve this. I'll explain at the end why I think this works in the docs but not for me.

### What is the expected behavior?

1) I'm able to connect to the weaviate cluster.

2) I'm able to ingest data with AWS embedding enabled `data.insert_many`.
This indicated that the credentials are valid and are being picked up from the headers.

3) I should be able to use `generate.near_text` to use an AWS. This is where the bug occurs.

### What is the actual behavior?

When I try to use `generate.near_text` I get the following error
```
AWS Access Key: no access key found neither in request header: X-AWS-Access-Key nor in environment variable under AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY
```

I've found that setting the environment variables in docker compose does work:
```yaml
environment:
      ...
      AWS_ACCESS_KEY: '<your-access-key>'
      AWS_SECRET_KEY: '<your-secret-key>'
```

What I believe is happening is the following:

- As you can see from the error, there are two ways of setting credentials, either by using the headers like the docs indicate or alternatively by setting the correct environment variables.
- The documentation, accidentally(?), does both. Thus covering the fact that the headers do not work for the `generate.near_text` method.
- Because I used a `.env` file, my environment variables were never really set, hence I do see the error.

### Supporting information

Here is my full docker compose file
```yaml
services:
  weaviate:
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.8
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-aws,generative-aws'
      # AWS_ACCESS_KEY: '<your-access-key>' # don't use these to reproduce the error
      # AWS_SECRET_KEY: '<your-secret-key>' # don't use these to reproduce the error
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
    driver: local
```

As for the python code follow the documentation at:
https://weaviate.io/developers/weaviate/model-providers/aws/embeddings

But don't use a `.env` file or any other means of keeping the environment variables unset. For example use a different name for the variables.

### Server Version

cr.weaviate.io/semitechnologies/weaviate:1.24.8

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
