### ISSUE TITLE
Weaviate text2vec-contextionary Module Fails to Retrieve Extensions

### ISSUE THREAD

**Issue by cesarqdt** [weaviate/weaviate#7239]
### How to reproduce this bug?

1. Deploy Weaviate with the above Helm command and values.yaml configuration.
2. Check the logs of the text2vec-contextionary pod.
3. Observe repeated "connection refused" errors when attempting to retrieve extensions from Weaviate.

After deploying Weaviate with the text2vec-contextionary module enabled using Helm, the module fails to retrieve extensions from Weaviate, logging multiple "connection refused" errors.

## Helm Installation Command:
```
helm upgrade --install \
        "weaviate" \
        weaviate/weaviate \
        --namespace "weaviate" \
        --values ./k8s/weaviate/values.yaml
```

## Values.yaml Configuration
```
text2vec-contextionary:
    enabled: true
    fullnameOverride: contextionary
    tag: en0.16.0-v1.2.1
    repo: semitechnologies/contextionary
    registry: cr.weaviate.io
    replicas: 1
    strategy:
      type: RollingUpdate
    imagePullPolicy: IfNotPresent
    imagePullSecrets: []
    priorityClassName: ""
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
      timeoutSeconds: 3
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 3
    envconfig:
      occurrence_weight_linear_factor: 0.75
      neighbor_occurrence_ignore_percentile: 5
      enable_compound_splitting: false
      extensions_storage_mode: weaviate
    resources:
      requests:
        cpu: '500m'
        memory: '500Mi'
      limits:
        cpu: '1000m'
        memory: '5000Mi'
```

## Observed Logs
```
{"action":"extensions_retrieve_all","error":"Get http://weaviate.weaviate.svc.cluster.local./v1/modules/text2vec-contextionary/extensions-storage/: dial tcp 10.0.243.174:80: connect: connection refused","level":"error","msg":"","time":"2025-02-13T12:54:47Z"}
```

### What is the expected behavior?

The module should successfully connect to Weaviate and retrieve the required extensions without errors.

### What is the actual behavior?

The module repeatedly fails to retrieve extensions, logging connection refused errors.

## Troubleshooting Attempts:

* Verified that the Weaviate pod is running and healthy.
* Checked the Weaviate service (kubectl get svc -n weaviate) and confirmed that it is correctly exposed.
I checked the container's URL setup for the EXTENSIONS_STORAGE_ORIGIN and the value seems to be correct by default:

```
    - name: EXTENSIONS_STORAGE_ORIGIN
      value: http://weaviate.weaviate.svc.cluster.local.
```

### Server Version

1.28.4

### Weaviate Setup

Multi-Node Cluster

### Nodes count

3

### Code of Conduct

- [x] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
