### ISSUE TITLE
Non-determinism when concurrently deleting cross references

### ISSUE THREAD

**Issue by thearchitector** [weaviate/weaviate#7879]
I'm not sure whether this is specifically a client issue, but I seem to be encountering a weird condition where concurrently deleting cross references from a collection (via `asyncio.gather`) results in non-deterministic/incorrect behavior, and more often than not seems to result in unexpected data when running in a multi-node setup.

Specifically, an operation like the following won't actually trigger any "Failed to delete" errors, but the assertion will fail because the number of cross references will be some random number more than 0 (what it should be).
```python
# bulk delete all cross refs
await asyncio.gather(
    *[
        e_col.data.reference_delete(e_uuid, "field_value_links", link_uuid)
        for link_uuid in link_uuids
    ]
)

# fetch the entity, no links expected
e = await e_col.query.fetch_object_by_id(
    e_uuid, return_references=[QueryReference(link_on="field_value_links")]
)
ls = e.references["field_value_links"].objects
assert not ls, f"expected no references, got {len(ls)}"
```

Using `deletion_strategy=ReplicationDeletionStrategy.DELETE_ON_CONFLICT` for the collection(s) does not seem to have any effect nor does altering the `ConsistencyLevel`, though the latter does get rid of the occasional QUORUM error when there are a sufficient number of concurrent deletions:
```
weaviate.exceptions.UnexpectedStatusCodeError: Reference was not deleted.! Unexpected status code: 500, with
response body: {'error': [{'message': 'msg:source object code:500 err:repo: object by id: search index event:
cannot achieve consistency level "QUORUM": read repair error: overwrite source object changed during repair
172.19.0.6:7101: conflict'}]}.
```

Changing the code to use a for loop instead of `asyncio.gather` somehow solves this issue:
```py
for link_uuid in link_uuids:
    await e_col.data.reference_delete(e_uuid, "field_value_links", link_uuid)
```

It also does not show up if there is only 1 reference to delete.

I am running a 3 node setup on K8s, but I see the same behavior locally via Docker Compose. It happens with almost 100% certainty when running multiple nodes locally, and is more 1/10 when running a single Weaviate instance locally or in my beefier multi-node production cluster.

This is on Python 3.10 and both the latest client and latest Weaviate versions, though affects older ones as well.

<details>

<summary>Files to reproduce:</summary>
<details>

<summary>docker-compose.yaml</summary>

```yaml
services:
  weaviate:
    image: semitechnologies/weaviate:1.30.1
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      AUTOSCHEMA_ENABLED: "false"
      ASYNC_INDEXING: "true"
      DISABLE_TELEMETRY: "true"
      # LOG_LEVEL: 'debug'
      # CLUSTER_HOSTNAME: 'node1'
      # CLUSTER_GOSSIP_BIND_PORT: '7100'
      # CLUSTER_DATA_BIND_PORT: '7101'
      # RAFT_JOIN: 'node1,node2,node3'
      # RAFT_BOOTSTRAP_EXPECT: 3
    volumes:
      - /var/lib/weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - 8080:8080
      - 6060:6060
      - 50051:50051
    init: true
    restart: on-failure:0
    healthcheck:
      test:
        ["CMD-SHELL", "wget --spider -q localhost:8080/v1/.well-known/ready"]
      interval: 2s
      timeout: 2s
      retries: 50

  # weaviate-2:
  #   image: semitechnologies/weaviate:1.30.1
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 100
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  #     PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  #     # ENABLE_MODULES: text2vec-transformers,reranker-transformers
  #     # DEFAULT_VECTORIZER_MODULE: text2vec-transformers
  #     # TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
  #     # RERANKER_INFERENCE_API: http://reranker-transformers:8080
  #     AUTOSCHEMA_ENABLED: "false"
  #     ASYNC_INDEXING: "true"
  #     DISABLE_TELEMETRY: "true"
  #     # LOG_LEVEL: 'debug'
  #     CLUSTER_HOSTNAME: 'node2'
  #     CLUSTER_GOSSIP_BIND_PORT: '7102'
  #     CLUSTER_DATA_BIND_PORT: '7103'
  #     CLUSTER_JOIN: 'weaviate:7100'
  #     RAFT_JOIN: 'node1,node2,node3'
  #     RAFT_BOOTSTRAP_EXPECT: 3
  #   volumes:
  #     - /var/lib/weaviate
  #   command:
  #     - --host
  #     - 0.0.0.0
  #     - --port
  #     - "8080"
  #     - --scheme
  #     - http
  #   restart: on-failure:0
  #   ports:
  #   - 8081:8080
  #   - 6061:6060
  #   - 50052:50051
  #   init: true
  #   healthcheck:
  #     test:
  #       ["CMD-SHELL", "wget --spider -q localhost:8080/v1/.well-known/ready"]
  #     interval: 2s
  #     timeout: 2s
  #     retries: 50

  # weaviate-3:
  #   image: semitechnologies/weaviate:1.30.1
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 100
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
  #     PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  #     # ENABLE_MODULES: text2vec-transformers,reranker-transformers
  #     # DEFAULT_VECTORIZER_MODULE: text2vec-transformers
  #     # TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
  #     # RERANKER_INFERENCE_API: http://reranker-transformers:8080
  #     AUTOSCHEMA_ENABLED: "false"
  #     ASYNC_INDEXING: "true"
  #     DISABLE_TELEMETRY: "true"
  #     # LOG_LEVEL: 'debug'
  #     CLUSTER_HOSTNAME: 'node3'
  #     CLUSTER_GOSSIP_BIND_PORT: '7104'
  #     CLUSTER_DATA_BIND_PORT: '7105'
  #     CLUSTER_JOIN: 'weaviate:7100'
  #     RAFT_JOIN: 'node1,node2,node3'
  #     RAFT_BOOTSTRAP_EXPECT: 3
  #   volumes:
  #     - /var/lib/weaviate
  #   restart: on-failure:0
  #   command:
  #     - --host
  #     - 0.0.0.0
  #     - --port
  #     - "8080"
  #     - --scheme
  #     - http
  #   ports:
  #   - 8082:8080
  #   - 6062:6060
  #   - 50053:50051
  #   init: true
  #   healthcheck:
  #     test:
  #       ["CMD-SHELL", "wget --spider -q localhost:8080/v1/.well-known/ready"]
  #     interval: 2s
  #     timeout: 2s
  #     retries: 50
```
</details>

<details>

<summary>script:</summary>

```python
import asyncio

from weaviate import WeaviateAsyncClient
from weaviate.classes.config import Configure, ReferenceProperty
from weaviate.classes.query import Filter, QueryReference
from weaviate.connect import ConnectionParams


async def delete_data_for_collection(
    client: "WeaviateAsyncClient", collection_name: str
) -> None:
    object_ids = []

    async for item in client.collections.get(collection_name).iterator():
        object_ids.append(item.uuid)

        # If the batch size is reached, delete the batch and reset it
        if len(object_ids) >= 100:
            await client.collections.get(collection_name).data.delete_many(
                where=Filter.by_id().contains_any(object_ids)
            )
            object_ids = []

    # Delete any remaining objects
    if object_ids:
        await client.collections.get(collection_name).data.delete_many(
            where=Filter.by_id().contains_any(object_ids)
        )


async def main() -> None:
    async with WeaviateAsyncClient(
        ConnectionParams.from_params(
            http_host="localhost",
            http_port=8080,
            http_secure=False,
            grpc_host="localhost",
            grpc_port=50051,
            grpc_secure=False,
        )
    ) as weav_client:
        print("hi")

        await weav_client.collections.delete_all()

        print("build")

        num_replicas = 1

        await weav_client.collections.create(
            name="FieldValueLink",
            vectorizer_config=Configure.Vectorizer.none(),
            vector_index_config=Configure.VectorIndex.none(),
            inverted_index_config=Configure.inverted_index(index_null_state=True),
            replication_config=Configure.replication(
                factor=num_replicas,
                async_enabled=True,
                # deletion_strategy=ReplicationDeletionStrategy.DELETE_ON_CONFLICT,
            ),
        )

        await weav_client.collections.create(
            name="Event",
            vectorizer_config=Configure.Vectorizer.none(),
            vector_index_config=Configure.VectorIndex.none(),
            inverted_index_config=Configure.inverted_index(
                index_null_state=True, index_timestamps=True
            ),
            references=[
                ReferenceProperty(
                    name="field_value_links", target_collection="FieldValueLink"
                ),
            ],
            replication_config=Configure.replication(
                factor=num_replicas, async_enabled=True
            ),
        )

        print("start")

        fvl_col = weav_client.collections.get("FieldValueLink")
        # .with_consistency_level(
        #     ConsistencyLevel.ALL
        # )
        e_col = weav_client.collections.get("Event")
        # .with_consistency_level(
        #     ConsistencyLevel.ALL
        # )

        for i in range(10):
            # make some links
            N = 10
            link_uuids = [await fvl_col.data.insert({}) for _ in range(N)]

            # make 1 event
            e_uuid = await e_col.data.insert({})

            # cross-ref links to the event
            await e_col.data.reference_replace(e_uuid, "field_value_links", link_uuids)

            # fetch the event, fetch the num links is expected
            e = await e_col.query.fetch_object_by_id(
                e_uuid, return_references=[QueryReference(link_on="field_value_links")]
            )
            assert len(e.references["field_value_links"].objects) == N, (
                f"expected {N} links, got {len(e.references['field_value_links'].objects)}"
            )

            # bulk delete all cross refs
            await asyncio.gather(
                *[
                    e_col.data.reference_delete(e_uuid, "field_value_links", link_uuid)
                    for link_uuid in link_uuids
                ]
            )

            # fetch the event, no links expected
            e = await e_col.query.fetch_object_by_id(
                e_uuid, return_references=[QueryReference(link_on="field_value_links")]
            )
            ls = e.references["field_value_links"].objects
            assert not ls, f"expected no references, got {len(ls)}"

            print(f"loop {i}")

            # delete all event and link data
            await delete_data_for_collection(weav_client, "FieldValueLink")
            await delete_data_for_collection(weav_client, "Event")


if __name__ == "__main__":
    asyncio.run(main())
```

</details>
</details>

With the setup above, a failing run looks like this (note the 2 successful loops before the sporadic failure):
```
$ python -Wignore script.py
hi
build
start
loop 0
loop 1
Traceback (most recent call last):
  File "/home/indico/snc/lagoon/bin/seed_data.py", line 132, in <module>
    asyncio.run(main())
  File "/home/indico/.pyenv/versions/3.10.16/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/indico/.pyenv/versions/3.10.16/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/indico/snc/lagoon/bin/seed_data.py", line 122, in main
    assert not ls, f"expected no references, got {len(ls)}"
AssertionError: expected no references, got 1
```
